let id = 1;
const storeProducts = [
    {
        id:id++,
        title: "Catwoman",
        img: "ProductPictures/Catwoman.jpg",
        price: 10,
        company: "DC",
        info:
            "Meow Hatula",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id:id++,
        title: "Captain America",
        img: "ProductPictures/Captain America.jpg",
        price: 15,
        company: "Marvel",
        info:
            "I can do this all day",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id:id++,
        title: "Chucky",
        img: "ProductPictures/Chucky.jpg",
        price: 10,
        company: "Horror",
        info:
            "Here comes Chucky",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id:id++,
        title: "Deadpool",
        img: "ProductPictures/Deadpool.jpg",
        price: 15,
        company: "Marvel",
        info:
            "I am Iron Man",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id:id++,
        title: "Goku",
        img: "ProductPictures/Goku.jpg",
        price: 15,
        company: "Dragon Ball",
        info:
            "Kamehameha!!!",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id:id++,
        title: "Groot",
        img: "ProductPictures/Groot.jpg",
        price: 15,
        company: "Marvel",
        info:
            "I am Groot",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id:id++,
        title: "Hellboy",
        img: "ProductPictures/Hellboy.jpg",
        price: 10,
        company: "Comics",
        info:
            "Hey stinkey! Kitchen's closed!",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id:id++,
        title: "Hulk",
        img: "ProductPictures/Hulk.jpg",
        price: 15,
        company: "Marvel",
        info:
            "You don't want me to be angry",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id:id++,
        title: "Starlord",
        img: "ProductPictures/Starlord.jpg",
        price: 15,
        company: "Marvel",
        info:
            "Oh, I sorry. I don't know how this machine works",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id:id++,
        title: "Pennywise",
        img: "ProductPictures/It.jpg",
        price: 15,
        company: "Horror",
        info:
            "Want a balloon?",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id:id++,
        title: "Sasuke",
        img: "ProductPictures/Sasuke.jpg",
        price: 20,
        company: "Manga",
        info:
            "You're such a loser, Naruto.",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id:id++,
        title: "Tobi",
        img: "ProductPictures/Tobi.jpg",
        price: 20,
        company: "Manga",
        info:
            "I get it now. I'm in hell.",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id:id++,
        title: "Carrie",
        img: "ProductPictures/Carrie.jpg",
        price: 15,
        company: "Horror",
        info:
            "True sorrow is as rare as true love",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id:id++,
        title: "Ichigo",
        img: "ProductPictures/Ichigo.jpg",
        price: 20,
        company: "Manga",
        info:
            "If miracles only happen once, what are they called the second time?",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id:id++,
        title: "Naruto",
        img: "ProductPictures/Naruto.jpg",
        price: 20,
        company: "Manga",
        info:
            "Harem-no-jutsu",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id:id++,
        title: "2Pac",
        img: "ProductPictures/2Pac.jpg",
        price: 15,
        company: "Singers",
        info:
            "All eyes on me",
        inCart: false,
        count: 0,
        total: 0,
    },

    {
        id:id++,
        title: "Ygritte",
        img: "ProductPictures/Ygritte.jpg",
        price: 15,
        company: "Game Of Thrones",
        info:
            "You don't know nothing John Snow.",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id:id++,
        title: "Scarlet Witch",
        img: "ProductPictures/Scarlet Witch.jpg",
        price: 15,
        company: "Marvell",
        info:
            "You took everything from me.",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id:id++,
        title: "Thanos",
        img: "ProductPictures/Thanos.jpg",
        price: 25,
        company: "Marvell",
        info:
            "I am inevitable.",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id:id++,
        title: "Venom",
        img: "ProductPictures/Venom.jpg",
        price: 25,
        company: "Marvell",
        info:
            "So many snacks.",
        inCart: false,
        count: 0,
        total: 0,
    },

]

const signedProducts = [
    {
        id:id++,
        title: "Elsa",
        img: "SignedProductPictures/Elsa.jpg",
        price: 60,
        company: "Disney",
        info:
            "Autographed by Idina Menzel.",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id:id++,
        title: "Hulk",
        img: "SignedProductPictures/Hulk.jpg",
        price: 65,
        company: "Marvell",
        info:
            "Autographed by Mark Ruffalo.",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id:id++,
        title: "Kaecilius",
        img: "SignedProductPictures/Kaecilius.jpg",
        price: 65,
        company: "Marvell",
        info:
            "Autographed by Mads Mikkelsen.",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id:id++,
        title: "Carl",
        img: "SignedProductPictures/Carl.jpg",
        price: 55,
        company: "Disney",
        info:
            "Autographed by Ed Asner.",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id:id++,
        title: "Stan Lee",
        img: "SignedProductPictures/Stan Lee.jpg",
        price: 100,
        company: "Manga",
        info:
            "Autographed by Stan Lee.",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id:id++,
        title: "Vincent Vega",
        img: "SignedProductPictures/Vincent Vega.jpg",
        price: 75,
        company: "Pulp Fiction",
        info:
            "Autographed by John Travolta.",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id:id++,
        title: "Green Ranger",
        img: "SignedProductPictures/Green Ranger.jpg",
        price: 70,
        company: "Power Rangers",
        info:
            "Autographed by Jason David Frank.",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id:id++,
        title: "Piccolo",
        img: "SignedProductPictures/Piccolo.jpg",
        price: 60,
        company: "Dragon Ball",
        info:
            "Autographed by Christopher Sabat.",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id:id++,
        title: "Magneto",
        img: "SignedProductPictures/Magneto.jpg",
        price: 75,
        company: "X-Men",
        info:
            "Autographed by Stan Lee.",
        inCart: false,
        count: 0,
        total: 0,
    },
]

const keysProducts = [
    {
        id:id++,
        title: "Aquaman",
        img: "KeysProductPictures/Aquaman.jpg",
        price: 5,
        company: "DC",
        info:
            "Permission to come aboard.",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id:id++,
        title: "Captain America",
        img: "KeysProductPictures/Captain America.jpg",
        price: 5,
        company: "Marvell",
        info:
            "Language.",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id:id++,
        title: "Loki",
        img: "KeysProductPictures/Loki.jpg",
        price: 5,
        company: "Marvell",
        info:
            "Are you ever not going to fall for that?",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id:id++,
        title: "Miles Morales",
        img: "KeysProductPictures/Miles Morales.jpg",
        price: 5,
        company: "Sony",
        info:
            "Hey.",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id:id++,
        title: "Mysterio",
        img: "KeysProductPictures/Mysterio.jpg",
        price: 5,
        company: "Marvell",
        info:
            "You don't want any part of this.",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id:id++,
        title: "Rocket",
        img: "KeysProductPictures/Rocket.jpg",
        price: 5,
        company: "Marvell",
        info:
            "I live for the simple things... like how much this is gonna hurt.",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id:id++,
        title: "Thanos",
        img: "KeysProductPictures/Thanos.jpg",
        price: 5,
        company: "Marvell",
        info:
            "The hardest choices require the strongest wills.",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id:id++,
        title: "The Joker",
        img: "KeysProductPictures/The Joker.jpg",
        price: 5,
        company: "DC",
        info:
            "I am not someone who is loved. I'm an idea. A state of mind.",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id:id++,
        title: "Thor",
        img: "KeysProductPictures/Thor.png",
        price: 5,
        company: "Marvell",
        info:
            "Bring me Thanos.",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id:id++,
        title: "Toxic Rick",
        img: "KeysProductPictures/Toxic Rick.png",
        price: 5,
        company: "Rick & Morty",
        info:
            "Barp.",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id:id++,
        title: "War Machine",
        img: "KeysProductPictures/War Machine.jpg",
        price: 5,
        company: "Marvell",
        info:
            "I'm only gonna say this once: GET OUT!",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id:id++,
        title: "Wonder Woman",
        img: "KeysProductPictures/Wonder Woman.jpg",
        price: 5,
        company: "DC",
        info:
            "It is our sacred duty to defend the world.",
        inCart: false,
        count: 0,
        total: 0,
    },


]

export {storeProducts, signedProducts, keysProducts}